# Generated by Django 5.0 on 2026-09-22
import django.contrib.auth.models
import django.contrib.auth.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Member', 'Member (สมาชิกผู้ซื้อ/ผู้ขาย)'), ('Admin', 'Admin (ผู้ดูแลระบบ & คนกลาง Escrow)')], default='Member', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active (ปกติ)'), ('Banned', 'Banned (ระงับการใช้งาน)')], default='Active', max_length=20)),
                ('avatar', models.URLField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&h=200&q=80', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อเกม')),
                ('logo', models.URLField(max_length=500, verbose_name='รูปภาพโลโก้')),
            ],
            options={
                'verbose_name_plural': 'Game Categories',
            },
        ),
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อโพสต์')),
                ('description', models.TextField(verbose_name='รายละเอียดบัญชีเกม')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา (THB)')),
                ('image', models.URLField(max_length=500, verbose_name='รูปภาพประกอบ')),
                ('status', models.CharField(choices=[('Available', 'Available (พร้อมขาย)'), ('Pending', 'Pending (กำลังดำเนินการ/รอตรวจสลิป)'), ('Sold', 'Sold (ขายแล้ว)')], default='Available', max_length=20)),
                ('server', models.CharField(blank=True, max_length=100, null=True, verbose_name='เซิร์ฟเวอร์')),
                ('rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระดับแรงค์')),
                ('level', models.IntegerField(default=1, verbose_name='เลเวล')),
                ('skins_count', models.IntegerField(default=0, verbose_name='จำนวนสกิน')),
                ('original_email', models.BooleanField(default=True, verbose_name='เมลแท้')),
                ('battle_pass', models.BooleanField(default=False, verbose_name='Battle Pass')),
                ('secondary_verification', models.BooleanField(default=False, verbose_name='ยินดีตรวจบัตร ปชช.')),
                ('game_credentials_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='ข้อมูลรหัสสำหรับคนกลาง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงขาย')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gametrade_app.gamecategory', verbose_name='หมวดหมู่เกม')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อห้องแชท')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เปิดห้องแชท')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametrade_app.gamepost', verbose_name='ไอดีเกมที่เกี่ยวข้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งานที่เปิดแชท')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='ข้อความ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='ไฟล์แนบ (รูปภาพ/สลิป)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='วันและเวลาที่ส่ง')),
                ('is_read', models.BooleanField(default=False, verbose_name='สถานะการอ่าน')),
                ('is_system', models.BooleanField(default=False, verbose_name='ข้อความจากระบบคนกลาง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gametrade_app.chatroom', verbose_name='รหัสห้องแชท')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่งข้อความ')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('slip_image', models.URLField(max_length=500, verbose_name='ไฟล์สลิปการโอน')),
                ('status', models.CharField(choices=[('Pending', 'Pending (รอดำเนินการตรวจสลิป)'), ('Completed', 'Completed (สำเร็จ/ส่งมอบไอดีแล้ว)'), ('Cancelled', 'Cancelled (ยกเลิก/สลิปไม่ถูกต้อง)')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gametrade_app.gamepost', verbose_name='โพสต์ที่สั่งซื้อ')),
            ],
        ),
    ]
