# Generated by Django 5.1.15 on 2026-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametrade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='รูปภาพประกอบ'),
        ),
    ]
