# Generated by Django 5.1.15 on 2026-09-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametrade_app', '0002_alter_gamepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(upload_to='slips/', verbose_name='รูปสลิปการโอน'),
        ),
    ]
